name: Sync Docs to Wiki

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**' # Se déclenche dès que le dossier docs est modifié

jobs:
  sync-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload to Wiki
        uses: Andrew-Chen-Wang/github-wiki-action@v4
        with:
          path: docs/
        env:
          # Utilisez le même PAT_TOKEN que pour vos autres automatisations
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
