name: Sync Docs to Wiki

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'docs/**'
  workflow_dispatch: # Permet de lancer le workflow manuellement depuis l'onglet Actions

jobs:
  sync-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sync docs folder to Wiki
        uses: Andrew-Chen-Wang/github-wiki-action@v4
        with:
          path: docs/
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
